### PR TITLE
fixed pathing and 404

### PR DESCRIPTION
**Pull request by ROBOKiTTY**

### CODE REVIEW

**Comment by bozimmerman** [comment]
If there's a bug or problem associated with this change, can you fill me in on 
how to recreate it?

- Bo

**Comment by ROBOKiTTY** [comment]
Fresh install of CoffeeMUD, build and start server, go to http://localhost:27777, click play now. 404 due to pathing/files not found.

**Comment by bozimmerman** [comment]
OK, want to make sure that I haven't already fixed this some other way... as I can't repro this quite yet.

First off, "http://localhost:27744/pub", by itself,  SHOULD give a 404, because /web/pub/ is the root of the 27744 directory, and thus "http://localhost:27744/pub" should attempt to access the path /web/pub/pub/, which doesn't exist.

**Comment by bozimmerman** [comment]
Also, I have to ask: Are you using the SUN Java JVM, and not the OpenJVM?   Weird unreproduceable problems have followed OpenJVM with CoffeeMud since the day it was invented.

**Comment by ROBOKiTTY** [comment]
MOUNT/=/web/pub/ is there as by default. I'm using the Sun/Oracle JVM, on JDK-14, running on a fresh copy of the repo from git. The default options in pub.ini are MOUNT/=/web/pub/ and MOUNT/guides=/guides/

I looked on the live CoffeeMUD site, and the pathing is the same there but it works. Maybe you have an extra mount field in the live version, something like MOUNT/siplet=/siplet/ that isn't in the git version?

**Comment by bozimmerman** [comment]
I'm actually still using the stock pub.ini file settings.  Besides, MOUNT/siplet=/siplet/ wouldn't work for me, since I don't have a /opt/coffeemud/siplet directory

- Bo

**Comment by bozimmerman** [comment]
Oh, crap, I'm getting confused .. you are accessing 27777 -- the admin port.
You are supposed to access 27744 to get to the public pages.
try http://localhost:27744/  and then hit play

**Comment by ROBOKiTTY** [comment]
All the links to the public pages in /web/admin/index.cmvp point to host:27777/pub, so that's how I ended up there.

27744 works with both the original file paths and the paths in this PR.

**Comment by bozimmerman** [comment]
This will be fixed in the next build -- checkin' coming soon.

**Pull request closed without merging**
